-- Baseline: the schema that migrations 0000-0015 produced, as one file.
--
-- Generated by applying the old chain to an empty database and running
-- pg_dump --schema-only --no-owner --no-privileges -n public. The old chain
-- also carried store rows, a product harvest and fixes to both; none of that
-- is here. A fresh database gets its rows from the private collector's seed
-- or from a restored dump.
--
-- Its journal `when` equals the old 0015's, so a database that already ran
-- the old chain (production) treats this as applied and skips it. The
-- migrator compares timestamps only, never file contents.
--
-- pg_trgm is guarded as in the old 0002: without the extension, product
-- search still works, it just scans.
DO $$
BEGIN
  CREATE EXTENSION IF NOT EXISTS pg_trgm;
EXCEPTION WHEN insufficient_privilege THEN
  RAISE NOTICE 'pg_trgm not installed: product search falls back to a sequential scan';
END $$;
--> statement-breakpoint
CREATE TABLE public.alerts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    kind text NOT NULL,
    channel text NOT NULL,
    payload jsonb NOT NULL,
    sent_at timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE public.baselines (
    store_id text NOT NULL,
    field_null_rates jsonb NOT NULL,
    expected_row_count integer NOT NULL,
    value_ranges jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE public.basket_map (
    item_key text NOT NULL,
    store_id text NOT NULL,
    product_key text,
    url text,
    status text NOT NULL,
    via text,
    note text,
    why text,
    pricing_note text,
    category text,
    category_tier integer,
    candidates integer,
    target_size text,
    picked_at timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE public.incidents (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    store_id text,
    run_id bigint,
    kind text NOT NULL,
    evidence jsonb NOT NULL,
    state text DEFAULT 'open'::text NOT NULL,
    opened_at timestamp with time zone DEFAULT now() NOT NULL,
    resolved_at timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE public.items (
    key text NOT NULL,
    label text NOT NULL,
    tier text NOT NULL,
    "group" text NOT NULL,
    group_weight_note text,
    numbeo_equivalent text,
    normal_unit text NOT NULL,
    target_size jsonb NOT NULL,
    match jsonb NOT NULL,
    categories jsonb NOT NULL,
    min_base_quantity double precision,
    min_base_quantity_note text,
    spec_version integer DEFAULT 1 NOT NULL,
    index_quantity double precision,
    index_uom text,
    CONSTRAINT items_index_uom_matches_normal_unit CHECK ((((index_quantity IS NULL) AND (index_uom IS NULL)) OR ((index_quantity > (0)::double precision) AND (index_uom =
CASE normal_unit
    WHEN 'g'::text THEN 'kg'::text
    WHEN 'ml'::text THEN 'l'::text
    ELSE 'count'::text
END))))
);
--> statement-breakpoint
CREATE TABLE public.price_observations (
    id bigint NOT NULL,
    run_id bigint,
    store_id text NOT NULL,
    product_key text NOT NULL,
    observed_at timestamp with time zone NOT NULL,
    price numeric(12,4) NOT NULL,
    currency text NOT NULL,
    unit_price numeric(16,6),
    unit_price_basis text,
    in_stock boolean,
    change text NOT NULL,
    previous_price numeric(12,4),
    delta numeric(12,4)
);
--> statement-breakpoint
CREATE VIEW public.latest_price AS
 SELECT DISTINCT ON (store_id, product_key) id,
    run_id,
    store_id,
    product_key,
    observed_at,
    price,
    currency,
    unit_price,
    unit_price_basis,
    in_stock,
    change,
    previous_price,
    delta
   FROM public.price_observations
  ORDER BY store_id, product_key, id DESC;
--> statement-breakpoint
CREATE SEQUENCE public.price_observations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
--> statement-breakpoint
ALTER SEQUENCE public.price_observations_id_seq OWNED BY public.price_observations.id;
--> statement-breakpoint
CREATE TABLE public.products (
    store_id text NOT NULL,
    product_key text NOT NULL,
    name text NOT NULL,
    url text,
    category text,
    unit text,
    size_value double precision,
    size_uom text,
    size_quantity double precision,
    size_base_uom text,
    size_form text,
    size_approximate boolean DEFAULT false NOT NULL,
    first_seen timestamp with time zone NOT NULL,
    last_seen timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE public.runs (
    id bigint NOT NULL,
    store_id text,
    at timestamp with time zone DEFAULT now() NOT NULL,
    method text,
    trigger text,
    status text,
    rows integer DEFAULT 0 NOT NULL,
    unit_priced integer DEFAULT 0 NOT NULL,
    pages integer DEFAULT 0 NOT NULL,
    ceiling_reached boolean DEFAULT false NOT NULL,
    changes integer DEFAULT 0 NOT NULL,
    coverage text,
    findings jsonb,
    null_rate_pct numeric(5,2)
);
--> statement-breakpoint
CREATE SEQUENCE public.runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
--> statement-breakpoint
ALTER SEQUENCE public.runs_id_seq OWNED BY public.runs.id;
--> statement-breakpoint
CREATE TABLE public.stores (
    store_id text NOT NULL,
    name text NOT NULL,
    country text NOT NULL,
    currency text,
    method text,
    endpoint text,
    max_pages integer,
    coverage text,
    coverage_reason text,
    index_contributor boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
ALTER TABLE ONLY public.price_observations ALTER COLUMN id SET DEFAULT nextval('public.price_observations_id_seq'::regclass);
--> statement-breakpoint
ALTER TABLE ONLY public.runs ALTER COLUMN id SET DEFAULT nextval('public.runs_id_seq'::regclass);
--> statement-breakpoint
ALTER TABLE ONLY public.alerts
    ADD CONSTRAINT alerts_pkey PRIMARY KEY (id);
--> statement-breakpoint
ALTER TABLE ONLY public.baselines
    ADD CONSTRAINT baselines_pkey PRIMARY KEY (store_id);
--> statement-breakpoint
ALTER TABLE ONLY public.basket_map
    ADD CONSTRAINT basket_map_item_key_store_id_pk PRIMARY KEY (item_key, store_id);
--> statement-breakpoint
ALTER TABLE ONLY public.incidents
    ADD CONSTRAINT incidents_pkey PRIMARY KEY (id);
--> statement-breakpoint
ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_pkey PRIMARY KEY (key);
--> statement-breakpoint
ALTER TABLE ONLY public.price_observations
    ADD CONSTRAINT price_observations_pkey PRIMARY KEY (id);
--> statement-breakpoint
ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_store_id_product_key_pk PRIMARY KEY (store_id, product_key);
--> statement-breakpoint
ALTER TABLE ONLY public.runs
    ADD CONSTRAINT runs_pkey PRIMARY KEY (id);
--> statement-breakpoint
ALTER TABLE ONLY public.stores
    ADD CONSTRAINT stores_pkey PRIMARY KEY (store_id);
--> statement-breakpoint
CREATE INDEX idx_basket_map_product ON public.basket_map USING btree (store_id, product_key);
--> statement-breakpoint
CREATE INDEX idx_obs_at ON public.price_observations USING btree (observed_at);
--> statement-breakpoint
CREATE INDEX idx_obs_product ON public.price_observations USING btree (store_id, product_key, id);
--> statement-breakpoint
CREATE INDEX idx_products_name_browse ON public.products USING btree (name, store_id, product_key);
--> statement-breakpoint
CREATE INDEX idx_runs_store ON public.runs USING btree (store_id, at);
--> statement-breakpoint
ALTER TABLE ONLY public.baselines
    ADD CONSTRAINT baselines_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(store_id);
--> statement-breakpoint
ALTER TABLE ONLY public.basket_map
    ADD CONSTRAINT basket_map_item_key_items_key_fk FOREIGN KEY (item_key) REFERENCES public.items(key);
--> statement-breakpoint
ALTER TABLE ONLY public.basket_map
    ADD CONSTRAINT basket_map_store_id_product_key_products_store_id_product_key_f FOREIGN KEY (store_id, product_key) REFERENCES public.products(store_id, product_key);
--> statement-breakpoint
ALTER TABLE ONLY public.basket_map
    ADD CONSTRAINT basket_map_store_id_stores_store_id_fk FOREIGN KEY (store_id) REFERENCES public.stores(store_id);
--> statement-breakpoint
ALTER TABLE ONLY public.incidents
    ADD CONSTRAINT incidents_run_id_runs_id_fk FOREIGN KEY (run_id) REFERENCES public.runs(id);
--> statement-breakpoint
ALTER TABLE ONLY public.incidents
    ADD CONSTRAINT incidents_store_id_stores_store_id_fk FOREIGN KEY (store_id) REFERENCES public.stores(store_id);
--> statement-breakpoint
ALTER TABLE ONLY public.price_observations
    ADD CONSTRAINT price_observations_run_id_runs_id_fk FOREIGN KEY (run_id) REFERENCES public.runs(id);
--> statement-breakpoint
ALTER TABLE ONLY public.price_observations
    ADD CONSTRAINT price_observations_store_id_product_key_products_store_id_produ FOREIGN KEY (store_id, product_key) REFERENCES public.products(store_id, product_key);
--> statement-breakpoint
ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_store_id_stores_store_id_fk FOREIGN KEY (store_id) REFERENCES public.stores(store_id);
--> statement-breakpoint
ALTER TABLE ONLY public.runs
    ADD CONSTRAINT runs_store_id_stores_store_id_fk FOREIGN KEY (store_id) REFERENCES public.stores(store_id);
--> statement-breakpoint
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_trgm') THEN
    CREATE INDEX IF NOT EXISTS idx_products_name_trgm
      ON public.products USING gin (name public.gin_trgm_ops);
  END IF;
END $$;
