#!/usr/bin/env node
/**
 * Generate migration 0012_local_harvest.sql from the local database: the
 * Aug 23 runs, products and price observations the zombie salvage and the
 * product-page pulls landed locally. Prod receives the data through the
 * deploy's migration runner -- no manual prod ops, no second spend.
 *
 * Run ids are shifted by +100000 so they cannot collide with prod's own
 * sequence; the sequence is bumped past them afterwards.
 */
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const require_ = createRequire(path.join(repo, "apps", "api", "package.json"));
const postgres = require_("postgres");

const DB_URL = process.env.DATABASE_URL ?? "postgres://basketwatch:basketwatch@localhost:5432/basketwatch";
const sql = postgres(DB_URL, { max: 1, onnotice: () => {} });
const OFFSET = 100000;
const DAY = "2026-08-23";

const esc = (v) => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  if (v instanceof Date) return `'${v.toISOString()}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const chunk = (arr, n) => {
  const out = [];
  for (let i = 0; i < arr.length; i += n) out.push(arr.slice(i, i + n));
  return out;
};

async function main() {
  const runs = await sql`
    select id, store_id, at, method, transport, source, "trigger", status,
           rows, unit_priced, pages, ceiling_reached, changes, coverage
    from runs where at::date = ${DAY} and status = 'ok' and source = 'studio'
    order by id`;
  const runIds = runs.map((r) => r.id);
  const stores = [...new Set(runs.map((r) => r.store_id))];

  const products = await sql`
    select store_id, product_key, name, url, category, unit, size_value, size_uom,
           size_quantity, size_base_uom, size_form, size_approximate, first_seen, last_seen
    from products
    where store_id = any(${stores}) and last_seen::date = ${DAY}
    order by store_id, product_key`;

  const obs = await sql`
    select run_id, store_id, product_key, observed_at, price, currency, unit_price,
           unit_price_basis, in_stock, source, change, previous_price, delta
    from price_observations
    where run_id = any(${runIds.map(Number)})
    order by run_id, product_key`;

  const lines = [];
  lines.push(`-- The Aug 23 harvest: every run, product and price observation the`);
  lines.push(`-- local salvage collected (zombie listing datasets + the converted`);
  lines.push(`-- product-page pulls). Generated by lab/scripts/dump-harvest.mjs;`);
  lines.push(`-- run ids are shifted +${OFFSET} to stay clear of prod's sequence.`);
  lines.push(``);

  for (const r of runs) {
    lines.push(
      `INSERT INTO runs (id, store_id, at, method, transport, source, "trigger", status, rows, unit_priced, pages, ceiling_reached, changes, coverage)` +
        ` VALUES (${Number(r.id) + OFFSET}, ${esc(r.store_id)}, ${esc(r.at)}, ${esc(r.method)}, ${esc(r.transport)}, ${esc(r.source)}, ${esc(r.trigger)}, ${esc(r.status)}, ${r.rows}, ${r.unit_priced}, ${r.pages}, ${r.ceiling_reached}, ${r.changes}, ${esc(r.coverage)})` +
        ` ON CONFLICT (id) DO NOTHING;`,
    );
  }
  lines.push(``);

  for (const batch of chunk(products, 500)) {
    const values = batch
      .map(
        (p) =>
          `(${esc(p.store_id)}, ${esc(p.product_key)}, ${esc(p.name)}, ${esc(p.url)}, ${esc(p.category)}, ${esc(p.unit)}, ${esc(p.size_value)}, ${esc(p.size_uom)}, ${esc(p.size_quantity)}, ${esc(p.size_base_uom)}, ${esc(p.size_form)}, ${p.size_approximate ?? false}, ${esc(p.first_seen)}, ${esc(p.last_seen)})`,
      )
      .join(",\n  ");
    lines.push(
      `INSERT INTO products (store_id, product_key, name, url, category, unit, size_value, size_uom, size_quantity, size_base_uom, size_form, size_approximate, first_seen, last_seen)\nVALUES\n  ${values}\n` +
        `ON CONFLICT (store_id, product_key) DO UPDATE SET\n` +
        `  name = excluded.name, url = excluded.url, last_seen = excluded.last_seen;`,
    );
    lines.push(``);
  }

  for (const batch of chunk(obs, 500)) {
    const values = batch
      .map(
        (o) =>
          `(${Number(o.run_id) + OFFSET}, ${esc(o.store_id)}, ${esc(o.product_key)}, ${esc(o.observed_at)}, ${o.price}, ${esc(o.currency)}, ${esc(o.unit_price)}, ${esc(o.unit_price_basis)}, ${o.in_stock}, ${esc(o.source)}, ${esc(o.change)}, ${esc(o.previous_price)}, ${esc(o.delta)})`,
      )
      .join(",\n  ");
    lines.push(
      `INSERT INTO price_observations (run_id, store_id, product_key, observed_at, price, currency, unit_price, unit_price_basis, in_stock, source, change, previous_price, delta)\nVALUES\n  ${values};`,
    );
    lines.push(``);
  }

  lines.push(`SELECT setval('runs_id_seq', GREATEST((SELECT COALESCE(max(id), 1) FROM runs), ${OFFSET + 200}));`);
  lines.push(``);

  const out = path.join(repo, "apps", "api", "drizzle", "0012_local_harvest.sql");
  writeFileSync(out, lines.join("\n"));
  console.log(
    `${out}: ${runs.length} runs, ${products.length} products, ${obs.length} observations, ` +
      `${Math.round(lines.join("\n").length / 1024)} KB`,
  );
}

main()
  .then(() => sql.end())
  .catch(async (e) => {
    console.error(e);
    await sql.end();
    process.exit(1);
  });
